#!/usr/bin/python
#
# Upstream - log file aggregator and report tool for *nix systems.
# Copyright (C) 2006  Mahangu Weerasinghe (mahangu@gmail.com)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import dialog, sys
from getpass import getuser
import  submitmoduleloader, logmoduleloader 

def main():
	d = dialog.Dialog(dialog="dialog")
	d.add_persistent_args(["--backtitle", "Upstream Log Transfer System"])
	
	#Step 1
	d.msgbox("This program will assist you in sending troubleshooting data to aid support personnel in diagnosing problems on your system.")
	
	#Step 2
	nickname = getuser()
	upnickname = ""
	
	while upnickname == "":
		(code, upnickname) = d.inputbox("Please enter your nickname", init="%s"%(nickname))
		
		if upnickname == "":
			d.msgbox("Sorry, but you didn't specify a name to use. Please try again, or hit CTRL+C to exit this program.")
			
	

	
	#Step 3
	log_modules.join()
	catchoices = []
	
	for cat in log_modules.getCategories():	
		catentry = (cat, "", 0)
		catchoices.append(catentry)
	
	
	log_dict = {}
		
	while log_dict == {}:
		(code, categories) = d.checklist(text="Please select categories this problem affects",
					height=15, width=54, list_height=7, 
					choices=catchoices,
					title="Problem Description")
		
		
		
		
		for x in categories:
			category = log_modules.getModulesInCategory(x)
			
			for log_module in category:
				module = log_modules[log_module.module_name]
				(name, contents) = module.execute()
				log_dict[name] = contents 
		
		if log_dict == {}:
			d.msgbox("Sorry, but you didn't specify even one category to load logs from. Please try again, or hit CTRL+C to exit this program.")
		
	
	(code, description) = d.inputbox("Please enter a description of the problem as well", init="")
	

	#Step 4
	submit_modules.join()
	modchoices = []
	
	for mod in submit_modules:
		modentry = (mod.module_name, "", 0)
		modchoices.append(modentry)
		print modentry
	
	pastebin = ""
	
	while pastebin == "":
		(code, pastebin) = d.radiolist(text="Please select the server to submit troubleshooting data to.",
                	                  height=15, width=54, list_height=7, 
                        	          choices=modchoices,
                                	  title="Submit")
		if pastebin == "":
			d.msgbox("Sorry, but you didn't specify a server to submit to. Please try again, or hit CTRL+C to exit this program.")
				  
	
	print pastebin
	
	submit_module = submit_modules[pastebin]
	
	print submit_module
	
	submit_module.execute(nickname, description, log_dict)
		
if __name__ == "__main__": 
	
	log_modules = logmoduleloader.LogModuleLoader(["log-modules"], True)

	submit_modules = submitmoduleloader.SubmitModuleLoader(["submit-modules"], True)
	
	main()

