#!/usr/bin/python
#
# Upstream - log file aggregator and report tool for *nix systems.
# Copyright (C) 2006  Mahangu Weerasinghe (mahangu@gmail.com)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import dialog, sys, os, optparse, ConfigParser, gettext, locale, logsynchronizer, inputpluginloader, outputpluginloader, signal
from getpass import getuser

config = ConfigParser.ConfigParser()
config.readfp(open('../conf/upstream.conf'))
libsdir = config.get("paths","libsdir")

sys.path.append(libsdir)

locale_app = config.get("main","locale_app")
locale_dir = config.get("paths","localedir")

import submitmoduleloader, logmoduleloader, moduleloader, uconf
from util import make_log_tuple

submit_module_default = config.get("main", "submit_module_default")

confdir = config.get("paths","confdir")

gettext.install(locale_app, locale_dir, unicode=1)

def main():
	d = dialog.Dialog(dialog="dialog")
	d.add_persistent_args(["--backtitle", "Upstream Log Transfer System"])
	
	#Step 1
	d.msgbox(_("This program will assist you in sending troubleshooting data to support personnel."))
	
	#Step 2
	nickname = getuser()
	upnickname = ""
	
	while upnickname == "":
		(code, upnickname) = d.inputbox(_("Please enter your name."), init="%s"%(nickname))
		
		if upnickname == "":
			d.msgbox(_("Sorry, but you didn't specify a name to use. Please try again, or hit CTRL+C to exit this program."))
			
	nickname = upnickname

	
	#Step 3
	log_modules.join()
	catchoices = []
	
	for cat in log_modules.get_categories():	
		catentry = (cat, "", 0)
		catchoices.append(catentry)
	
	
	log_tuple = []
		
	while log_tuple == []:
		(code, categories) = d.checklist(text=_("What are you having trouble with?"),
					height=15, width=54, list_height=7, 
					choices=catchoices,
					title=_("Problem Description"))		
		
		# Codes from dialog.py, see dialog.py 423
		if code == 1 or code == 2:
			sys.exit(0)
		
		mods = log_modules.get_unique_in_categories(categories)
		nt_logmods = []
		t_logmods = []
					
				
		log_tuple = make_log_tuple(mods)
		
		if log_tuple == []:
			d.msgbox(_("Sorry, but you didn't specify even one category to load logs from. Please try again, or hit CTRL+C to exit this program."))
		
	
	(code, description) = d.inputbox(_("Please enter a short description of the problem."), init="")
	# Codes from dialog.py, see dialog.py 423
	if code == 1 or code == 2:
		sys.exit(0)


	#Step 4
	submit_modules.join()
	modchoices = []
	
	for mod in submit_modules:
		if mod.module_name == submit_module_default:
			modbool = 1
		else:
			modbool = 0
		
		modentry = (mod.module_name, "", modbool)
		modchoices.append(modentry)
	
	pastebin = ""
	
	while pastebin == "":
		(code, pastebin) = d.radiolist(text=_("Please select a server to submit to."),
                	                  height=15, width=54, list_height=7, 
                        	          choices=modchoices,
                                	  title=_("Submit"))
									  
		# Codes from dialog.py, see dialog.py 423
		if code == 1 or code == 2:
			sys.exit(0)
			
		if pastebin == "":
			d.msgbox(_("Sorry, but you didn't specify a server to submit to. Please try again, or hit CTRL+C to exit this program."))	
	submit_module = submit_modules[pastebin]
	
	execute_plugin(submit_module, nickname, description, log_tuple)
	
def cli(options,args):
	
	
	if os.isatty(sys.stdin.fileno()) == False:
		stdinput = sys.stdin.read()
		log_tuple = (("stdin","stdin",stdinput), )
	
	else:
		log_tuple = []
			
		optnumber = 0	
		
		log_modules.join()
		for x in options.__dict__.iteritems():
			option = x[0]
			on = x[1]
						
			# Is there a nicer way to do this?
			if on and option != "pastebin" and option != "log":
				category = log_modules.get_in_category(option)
				
				for log_module in category:
					log_tuple = make_log_tuple(category)
							
				optnumber = optnumber + 1
			
			elif options.log:
				category = log_modules.get_in_category(option)
				log_tuple = make_log_tuple(category)
			
				optnumber = optnumber + 1
				options.log = False
		
		# Check to see if all mandatory arguments have been filled.
		
				print _("%s log file(s) have been read.")%(optnumber)
				
				if optnumber < 1:
					print _("Please specify a log option. You haven't asked me to send anything. See help (-h) for more information.")
					sys.exit(1)
					
	submit_modules.join()			
	if options.pastebin:
			submit_module = submit_modules[options.pastebin]
	else:
			submit_module = submit_modules[submit_module_default]
	
	if len(args) != 2:
		print _("Please specify the required options. See help (-h) for more information.")
		sys.exit(1)
	
	
	#  Populating final variables.
	
	user_email = args[0]
	user_message = args[1]
	
	#user_logs = functions.get_final()
	execute_plugin(submit_module, user_email, user_message, log_tuple)


def ioctl_GWINSZ(fd):                  #### TABULATION FUNCTIONS
    try:                                ### Discover terminal width
        import fcntl, termios, struct, os
        cr = struct.unpack('hh', fcntl.ioctl(fd, termios.TIOCGWINSZ, '1234'))
    except:
        return None
    return cr

def terminal_size():  ### decide on *some* terminal size
    cr = ioctl_GWINSZ(0) or ioctl_GWINSZ(1) or ioctl_GWINSZ(2)  # try open fds
    if not cr:     # ...then ctty
        try:
            fd = os.open(os.ctermid(), os.O_RDONLY)
            cr = ioctl_GWINSZ(fd)
            os.close(fd)
        except:
            pass
    if not cr:                            # env vars or finally defaults
        try:
            cr = (env['LINES'], env['COLUMNS'])
        except:
            cr = (25, 80)
    return int(cr[1]), int(cr[0])  
		
def update_terminal_size(signum, frame):
	global col
	global row
	col, row = terminal_size()
		 		
def execute_plugin(submit_module, user_email, user_message, log_tuple):
	submit_module.execute_threaded(user_email, user_message, log_tuple)
	start = 0
	while submit_module.threaded_execute_is_running():
		print_pulser(start, col)
		start = (start + 1)%col
		submit_module.wait_for_threaded_execute(0.05)
		
	result = submit_module.threaded_result()
	sys.stdout.write('\r')
	for x in range(0, col):
		sys.stdout.write(' ')
	sys.stdout.write('\r')
	if result.bool_success:
		print _("Your submission was successful and can be found at:\n%s") % result.result_url
	else:
		print _("Your submission failed.")
	
		
# TODO: make this look nicer, its just a proof ofconceptnow

def print_pulser(start, size):
	mid = (start + 1)%size
	end = (start + 2)%size
	sys.stdout.write('\r')	
	index = 0
	if mid < start:
		sys.stdout.write("**")
		index = 2
		while index < start:
			sys.stdout.write(' ')
			index = index + 1
		sys.stdout.write("*")
	elif end < start:
		sys.stdout.write('*')
		index = 1
		while index < start:
			sys.stdout.write(' ')
			index = index + 1
		sys.stdout.write("**")
	else:
		while index < start:
			sys.stdout.write(' ')
			index = index + 1
		sys.stdout.write("***")
		index = index + 3
		while index < size:
			sys.stdout.write(' ')
			index = index + 1	
	# This is important so that stuff isn't ridiculously
	# slow for redrawing
	sys.stdout.flush()
	
if __name__ == "__main__": 
	logsync = logsynchronizer.LogSynchronizer(sys.stdout)
	l_config = uconf.PluginConfigReader(uconf.INPUT, confdir)
	log_modules = inputpluginloader.InputPluginLoader(l_config, logsync)

	s_config = uconf.PluginConfigReader(uconf.OUTPUT, confdir)
	submit_modules = outputpluginloader.OutputPluginLoader(s_config, logsync)
	
	parser = optparse.OptionParser(_("%prog yourname \"Your support message\" [options]. If no arguments are supplied, Upstream will go in to wizard mode."))
	log_modules.start()
	submit_modules.start()
	log_modules.join()
	submit_modules.join()
	categories = log_modules.get_categories()
	for category in categories:
		lflag = "--%s"%(category)
		# debug print
		#print lflag

		parser.add_option("", lflag, action="store_true", help=_("All log modules in the %s category.")%(category), default=False)

	parser.add_option("", "--pastebin", dest="pastebin", help=_("Specify a pastebin module to use."), default=False)

	parser.add_option("", "--log", dest="log", help=_("Choose a specific a log module to use."), default=False)

	(options, args) = parser.parse_args()
	col, row = terminal_size()
	signal.signal(signal.SIGWINCH, update_terminal_size)
	try:
		if args == []:
			main()
		else:
			cli(options,args)
	except Exception, e:
		logsync.dump()
		print _("An exception occured at some point during execution. Above is the complete log of all that occured while running the Plugin Loaders")
		

		

