#!/usr/bin/python
#
# Upstream - log file aggregator and report tool for *nix systems.
# Copyright (C) 2006  Mahangu Weerasinghe (mahangu@gmail.com)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import dialog, sys, time
from getpass import getuser
import  submitmoduleloader, logmoduleloader, uconf

import optparse, os, ConfigParser

config = ConfigParser.ConfigParser()
config.readfp(open('%s/upstream.conf'%(uconf.base_path_default)))
	

locale_app = config.get("main", "locale_app_name")
locale_dir = config.get("main", "locale_app_dir")

import locale
import gettext
#locale.setlocale(locale.LC_ALL, '')
gettext.bindtextdomain(locale_app, locale_dir)
gettext.textdomain(locale_app)
_ = gettext.gettext


def main():
	d = dialog.Dialog(dialog="dialog")
	d.add_persistent_args(["--backtitle", "Upstream Log Transfer System"])
	
	#Step 1
	#d.msgbox(_("This program will assist you in sending troubleshooting data to support personnel."))
	
	
if __name__ == "__main__": 
	
	submit_module_default = config.get("main", "submit_module_default")

	l_config = uconf.PluginConfigReader(uconf.LOG, "../conf")
	global log_modules
	log_modules = logmoduleloader.LogModuleLoader(l_config, True)

	s_config = uconf.PluginConfigReader(uconf.SUBMIT, "../conf")
	global submit_modules
	submit_modules = submitmoduleloader.SubmitModuleLoader(s_config, True, 1)
	
	#parser = optparse.OptionParser(_("%prog yourname \"Your support message\" [options]. If no arguments are supplied, Upstream will go in to wizard mode."))
	submit_modules.join()
	log_modules.join()	
	main()
	

